server:
  port: 9090
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #查看日志
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aqi?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: "020826"
